theme = "solarized-light"
icons = "awesome"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block = "net"
device = "wlp4s0"
ssid = true
speed_up = false
interval = 5

[[block]]
block = "cpu"

[[block]]
block = "memory"
interval = 5
info_type = "memory"
format_mem = "{Mupi}%"
clickable = false

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 3600

[[block]]
block = "battery"
format = "{percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 30
format = "%a %d/%m %R"

