export EDITOR=/usr/bin/nvim
export VISUAL=/usr/bin/nvim
export GDK_BACKEND=wayland
export CLUTTER_BACKEND=wayland
PATH="$HOME/bin:$PATH"
PATH="$HOME/.cargo/bin:$PATH"
PATH="$PATH:$HOME/.emacs.d/bin"
export _JAVA_AWT_WM_NONREPARENTING=1
export WEECHAT_HOME=$HOME/.config/weechat
export XDG_CONFIG_HOME=$HOME/.config
export VIMCONFIG=$HOME/.vim
