setlocal expandtab
setlocal shiftwidth=4
setlocal softtabstop=4
setlocal tabstop=4
setlocal softtabstop=4
setlocal textwidth=79
setlocal autoindent
setlocal fileformat=unix
setlocal wildignore=**/__pycache__/**,*.pyc,**/lib/**,**/lib64/**
